#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers



password=$YNH_APP_ARG_PASSWORD
ynh_app_setting_set --app=$app --key=password --value=$password

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..."

ynh_install_nodejs --nodejs_version=$nodejs_version

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:$app "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

# Create a dedicated systemd config
ynh_add_systemd_config

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
chown $app -R /var/log/$app

# Use logrotate to manage application logfile(s)
ynh_use_logrotate

yunohost service add $app --description="Transfer files or images" --log="/var/log/$app/$app.log"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL APP
#=================================================
ynh_script_progression --message="Installing $app..."

pushd $install_dir
 	ynh_use_nodejs
	ynh_exec_warn_less sudo -u $app env $ynh_node_load_PATH $ynh_npm install
popd

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..."

ynh_add_config --template="../conf/config.production.js" --destination="$install_dir/config.production.js"

chmod 400 "$install_dir/config.production.js"
chown $app:$app "$install_dir/config.production.js"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..."

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed"
